---
title: "Test per le organizzazioni"
author: "Ottavia Epifania & Margherita Calderan"
format: 
  html: 
   self-contained: true
   toc: true
   toc-location: left
   theme: minty
---

# Modulo 0

Il concetto di misura in psicologia [slides in PDF](slides/00-Misura/00-Misura.pdf)

# Modulo 1

Intoduzione a R

**1.0.** [Guida](slides/01-IntroR/guida.html) installazione R 

**1.1.**  Come lavorare in R [slides in PDF](slides/01-IntroR/0-R.pdf)

**1.2.**  Vettori, Fattori, Matrici, Dataframe [slides in PDF](slides/01-IntroR/1-R.pdf)

-   [Esercizio 1, con soluzioni](slides/01-IntroR/esercizi/vettori-fattori.R)
-   [Esercizio 2, con soluzioni](slides/01-IntroR/esercizi/dataframe.R)


**1.3.** [Riassunto](slides/01-IntroR/recap.html) concetti principali

# Modulo 2

Statistiche Descrittive

**2.0.**  Frequenze, Indici di Tendenza Centrale, Posizione, Variabilità, e Forma [slides in PDF](slides/02-StatBase/0-Descrittiva.pdf)
 
  - Dati (simulati) da [scaricare](slides/02-StatBase/data/burnout.csv){download="burnout.csv"}
  
**2.1.** [Riassunto](slides/02-StatBase/recapDescrittive.html) comandi e concetti principali.

  

# Modulo 3

Test di prestazione tipica e massima, scale di risposta, Validità e Attendibilità [slides in pdf](slides/03-Test/03-Test.pdf)

Il Big Five Inventory è uno strumento molto usato per la valutazione dei 5 fattori del Big Five. La verione originale si trova in: 

John, O. P., Donahue, E. M., & Kentle, R. L. (1991). *The Big Five Inventory—Versions 4a and 54*. Berkeley, CA: University of California, Berkeley, Institute of Personality and Social Research.

La validazione italiana e standardizzazione è a cura di Chiorri e colleghi:

Chiorri, C., Bracco, F., Piccinno, T., Modafferi, C., & Battini, V. (2015). Psychometric properties of a revised version of the Big Five Inventory (BFI) in an Italian sample. *Psychological Reports, 117*(1), 1–21.

**BFI** [Questionario](slides/03-Test/esempi-test/BFI.pdf)

**BFI** [Dati normativi](slides/03-Test/esempi-test/BFI_dati_normativi_completo.pdf)

# Modulo 4

Punteggi standardizzati, Distribuzione Normale, Distribuzioni di Probabiltà [slides in PDF](slides/02-StatBase/04-Probabilita.pdf)
