---
title: "Modulo Didattico 1: Il concetto di Misura"
subtitle: "Test per le organizzaioni"
author: Ottavia M. Epifania, Margherita Calderan
date: ""
format:
  beamer:
    slide-level: 3
    theme: Madrid
    colortheme: dove
    navigation: horizontal
    highlight-style: breeze
    classoption: compress, aspectratio=149
    innertheme: rounded
    outertheme: miniframes
callout-icon: false
code-annotations: below
header-includes: |
  \usepackage{graphicx}
  \usepackage[italian]{babel}
  \usepackage{xcolor}
  \usepackage{tikz}
  \usetikzlibrary{mindmap,calc,patterns,decorations.pathmorphing,decorations.markings,arrows,shapes.arrows,shapes.geometric,backgrounds,positioning,shadows.blur}
  \usepackage[absolute,overlay]{textpos}

  \tikzstyle{latent} = [ellipse, minimum width=2.5cm, minimum height=2cm,text centered, draw=black]
  \tikzstyle{item} = [rectangle, rounded corners, minimum width=0.5cm, minimum height=2cm, text width =1.7cm, text centered, draw=black]
  \tikzstyle{arrow} = [thick,->,>=stealth]
  \newcommand{\tikzoverlay}[1]{\tikz[remember picture,overlay] #1}

  \AtBeginSubsection{}

  \AtBeginDocument{\institute[]{Università di Padova}}
  \AtBeginDocument{\author{\textbf{Ottavia M. Epifania}\\\texttt{ottavia.epifania@unipd.it}\\[0.5em]Margherita Calderan\\\texttt{margherita.calderan@unipd.it}}}

  \AtBeginSection[]
  {
    \begin{frame}[plain]
      \tableofcontents[currentsection, hideallsubsections]
    \end{frame}
  }

  \AtBeginSubsection[]
  {
    \begin{frame}[plain]
      \tableofcontents[currentsection,currentsubsection,hideothersubsections]
    \end{frame}
  }
editor_options: 
  chunk_output_type: console
execute: 
  echo: true
---

# Il corso 

## Orari

### 

Lezioni:

- Lunedì: 12:30-15:30 

*Lunedì 6 aprile non ci sarà lezione*

Ricevimento: su appuntamento, prevalentemente online

\begin{center}
ottavia.epifania@unipd.it \\
margherita.calderan@unipd.it
\end{center}

## Argomenti 

### 

Il corso prevede parti di natura teorica relativi agli aspetti della misura in psicologia (nel caso particolare dei test nel contesto organizzativo) sia da esercitazioni pratiche, dove vengono illustrate le procedure più comuni per l'analisi della dimensionalità dei test e delle loro caratteristiche in generale

Alcune delle tematiche: 

* Misurazione, scale di misura e statistiche adeguate 
* Rappresentazioni grafiche del dato
* Diversi tipi di test per diversi obiettivi misurativi
* Teoria classica dei test: Approccio esplorativo e confermativo 
* Applicazioni in R

### Esame 

L'esame avrà dura di 90 minuti, sarà composto da 20 domande, di cui 12 a risposta chiusa e 8 di interpretazione di output ottenuti con R 

Nelle domande a risposta aperta verranno valutati i seguenti criteri: 

* Chiarezza espositiva 
* Conoscenza dell'argomento
* Capacità di veicolare concetti complessi 

# La misura in psicologia

### 

:::{.callout-tip}
## Compito!

Siete responsabile HR in un'azienda e dovete scegliere un* nuov* project manager tra una rosa di candidati. Quale caratteristiche di personalità per voi sono fondamentali in un PM?

:::

. . . 

Alcune possibilità: 

* Leadership
* Stabilità emotiva
*	coscienziosità
*	teamwork
*	resilienza
*	assertività


### 

Cos'è la leadership? 

Come si misura la leadership?



### 

::: {.callout-note}
## Misura

Processo di assegnazione di numeri o simboli a proprietà di oggetti, eventi o fenomeni, seguendo regole definite e condivise per rappresentarne quantitativamente le proprietà e consentirne la descrizione, il confronto e l’analisi.

:::


```{=tex}
Vanno distinte le \textbf{quantità} dalle \textbf{qualità} delle unità di analisi 
	
\begin{columns}[T]
\begin{column}{.50\linewidth}
\begin{center}
Quantità
\end{center}
\small 

Si parla di \textbf{misurazione}
			
La \textbf{misura} esprime una manifestazione particolare della quantità
			
Le misure sono esprimibili con numeri che rappresentano una quantità
			
\begin{exampleblock}{Esempio:}
				
La larghezza della cattedra è una msiura della quantità ``lunghezza''
\end{exampleblock}
\end{column}
\pause
\begin{column}{.50\linewidth}
\begin{center}
Qualità
\end{center}
\small
			
Si parla di \textbf{rilevazione}
			
Sono caratteristiche che variano da un'unità di analisi all'altra ma non sono quantità 
			
Le misure delle qualità si esprimono con simboli (anche numerici) ma \textbf{i numeri non esprimono misure di quantità}
			
\begin{exampleblock}{Esempio:}
				
Luogo di nascita degli studenti di questa classe
\end{exampleblock}
\end{column}
\end{columns}
```

### 

```{=tex}
\begin{tikzpicture}[remember picture,overlay]

\node (n1) at ([yshift=2cm]current page.center) {
\begin{minipage}{0.7\textwidth}
\begin{block}{}
Sistema relazionale numerico

I numeri naturali con le loro proprietà $\rightarrow$:

\begin{itemize}
\item Stabilire una relazione d'ordine ($>$, $<$, $=$)
\item Operazioni
\end{itemize}

\end{block}
\end{minipage}
};

\node (n2) at ([yshift=-2cm]current page.center) {
\begin{minipage}{0.7\textwidth}
\begin{block}{}
Sistema relazionale empirico

Proprietà degli oggetti
\end{block}
\end{minipage}
};

\path [line width=0.04cm,<->] (n1.south) edge node[anchor=east] {Regola} (n2.north);

\end{tikzpicture}
```



## Un esempio 

### 


```{=tex}
\begin{tikzpicture}
\draw[-,thick] (0,-6) -- (8,-6) node[right] {bastoncino $a$};
\draw[-,thick] (0,-7) -- (4,-7) node[right] {bastoncino $b$};
\end{tikzpicture}

Il bastoncino $a$ è lungo il doppio del bastoncino $b$: 

\begin{block}{Relazione numerica}
$b = \dfrac{1}{2}a$ oppure $a = 2b$

\vspace{1.5mm}
Se aggiungiamo una costante $k$ ad $a$ e $b$, il rapporto tra $a$ e $b$ non cambia
\end{block}

Il sistema relazionale numerico è in relazione diretta con il sistema relazione empirico

Le variabili psicologiche non fanno parte del sistema relazionale empirico! Come si possono quantificare? Come si possono misurare?
```

