---
title: "Esercitazione-CFA"
author: "Ottavia"
format: 
  html: 
   self-contained: true
   toc: true
   toc-location: left
   theme: sandstone
execute: 
  echo: false
  message: false
  warning: false
editor_options: 
  chunk_output_type: console
---

```{r setup, include = FALSE}
library(MASS)
library(tidyverse)
library(lavaan)
library(psych)
library(corrplot)
mycolorsI = rep(c("#E69F00",
"#56B4E9",
"#009E73",
"#CC79A7",
"#D55E00"), each = 10)
mycolorsF = factor(unique(mycolorsI))
plot_lambda = function(objLav, index = 1) {
   mylambda = as.data.frame(objLav$loadings[[index]])
mylambda$item = rownames(mylambda)
mylambda = pivot_longer(mylambda, cols = !item)
g = ggplot(mylambda, 
       aes(x = name, y = item, fill = value)) + geom_tile() + 
    scale_fill_gradient2(
    low = "firebrick",     # valori negativi
    mid = "white",    # zero
    high = "midnightblue",     # valori positivi
    midpoint = 0,     # centro = 0
    limits = c(-1, 1) # limiti fissati
  ) + theme_light() + 
  theme(legend.title = element_blank(), 
        legend.position = "top", 
        legend.text = element_text(size = 20), 
        axis.title = element_blank(), 
        axis.text = element_text(size = 20), 
        legend.key.width = unit(1.5, "cm"),
  legend.key.height = unit(0.8, "cm"))
  return(g)
}

load("efa-env.RData")
defa = d
d = data[data$filter %in% 1, colnames(data) %in% unlist(labels)]

mycor = list()
myrev = list()

for(i in 1:length(names(labels))) {
  mycor[[i]] = cor(d[, colnames(d) %in% labels[[i]]])
  names(mycor)[i] = names(labels)[i]
  myrev[[i]] = names(mycor[[i]][,1][mycor[[i]][,1]< 0])
  names(myrev)[i] = names(labels)[i]
}
d[, colnames(d) %in% unlist(myrev[-3])] = 6 - d[, colnames(d) %in% unlist(myrev[-3])]
# nel caso di A devoisolare gli item
m = labels$A[!labels$A %in% myrev$A]
# devo fare la differenza simmetrica:gli item che sono in A ma che non sono in rev$A
d[, colnames(d) %in% m] = 6 - d[, colnames(d) %in% m]

for(i in 1:length(names(labels))) {
  mycor[[i]] = cor(d[, colnames(d) %in% labels[[i]]])
  names(mycor)[i] = names(labels)[i]
  myrev[[i]] = names(mycor[[i]][,1][mycor[[i]][,1]< 0])
  names(myrev)[i] = names(labels)[i]
}


rawd = d


labnew = labels
names(labnew) = paste0("F", 1:5)
colnames(rawd) = paste0("item", 1:ncol(rawd))

labnew[[1]] = colnames(rawd)[1:10]
labnew[[2]] = colnames(rawd)[11:20]
labnew[[3]] = colnames(rawd)[21:30]
labnew[[4]] = colnames(rawd)[31:40]
labnew[[5]] = colnames(rawd)[41:50]


model = paste(paste0("F1 =~ ", paste(labnew[["F1"]], collapse = " + ")),
paste0("F2 =~ ", paste(labnew[["F2"]], collapse = " + ")), 
paste0("F3 =~ ", paste(labnew[["F3"]], collapse = " + ")), 
paste0("F4 =~ ", paste(labnew[["F4"]], collapse = " + ")), 
paste0("F5 =~ ", paste(labnew[["F5"]], collapse = " + ")),
sep = "\n ")

m = cfa(model, data=rawd, std.lv = TRUE)
summary(m)

mord = cfa(model, data=rawd, std.lv = TRUE, ordered = colnames(rawd))
summary(mord)
```

# Big Five


```{r}
library(knitr)
library(kableExtra)

items <- data.frame(
  Item = paste0("item", 1:50),
  Description = c(
    "I am the life of the party.",
    "I don't talk a lot.",
    "I feel comfortable around people.",
    "I keep in the background.",
    "I start conversations.",
    "I have little to say.",
    "I talk to a lot of different people at parties.",
    "I don't like to draw attention to myself.",
    "I don't mind being the center of attention.",
    "I am quiet around strangers.",
    
    "I get stressed out easily.",
    "I am relaxed most of the time.",
    "I worry about things.",
    "I seldom feel blue.",
    "I am easily disturbed.",
    "I get upset easily.",
    "I change my mood a lot.",
    "I have frequent mood swings.",
    "I get irritated easily.",
    "I often feel blue.",
    
    "I feel little concern for others.",
    "I am interested in people.",
    "I insult people.",
    "I sympathize with others' feelings.",
    "I am not interested in other people's problems.",
    "I have a soft heart.",
    "I am not really interested in others.",
    "I take time out for others.",
    "I feel others' emotions.",
    "I make people feel at ease.",
    
    "I am always prepared.",
    "I leave my belongings around.",
    "I pay attention to details.",
    "I make a mess of things.",
    "I get chores done right away.",
    "I often forget to put things back in their proper place.",
    "I like order.",
    "I shirk my duties.",
    "I follow a schedule.",
    "I am exacting in my work.",
    
    "I have a rich vocabulary.",
    "I have difficulty understanding abstract ideas.",
    "I have a vivid imagination.",
    "I am not interested in abstract ideas.",
    "I have excellent ideas.",
    "I do not have a good imagination.",
    "I am quick to understand things.",
    "I use difficult words.",
    "I spend time reflecting on things.",
    "I am full of ideas."
  )
)

kable(items,
      format = "html",
      col.names = c("Item", "Description"),
      caption = "Items Questionnaire") %>%
  kable_styling(full_width = FALSE)
```


# Modelli 


```{r}
#| layout-ncol: 2
#| column: screen
#| label: fig-semPaths
#| fig-cap: "Modello Fattoriale Confermativo"
#| fig-subcap: 
#|   - "a"
#|   - "b"
library(semPlot)
semPaths(m, what = "est", style = "OpenMx", layout="tree2", 
         groups = labnew, color = mycolorsF)

semPaths(mord, what = "est", style = "OpenMx", layout="tree2", groups = labnew, color = mycolorsF)
```


```{r}
summary(m)
```

```{r}
summary(mord)
```

# Consistenza interna 

```{r}
myalphas = NULL

for (i in 1:length(names(labnew))) {
  temp = psych::alpha(rawd[, colnames(rawd) %in% labnew[[i]]])$total
  myalphas = rbind(myalphas, temp)
}
rownames(myalphas) = names(labnew)

apply(myalphas,2, round, digit = 2)
```

